[project]
name = "ha-auchan"
version = "0.1.0"
requires-python = ">=3.14"

[dependency-groups]
dev = [
    "pytest",
    "pytest-homeassistant-custom-component",
    "pylint",
]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.pylint.main]
init-hook = "import sys; sys.path.insert(0, '/workspaces/ha-auchan')"