"""Config flow for Auchan."""

from collections.abc import Mapping
import logging
import secrets
from typing import Any, cast, override

from aiohttp import ClientError
import probatio

from homeassistant.config_entries import SOURCE_REAUTH, ConfigFlowResult
from homeassistant.helpers import config_entry_oauth2_flow
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .api import async_get_user_info_for_setup
from .const import DOMAIN
from .oauth import AuchanOAuth2Implementation, async_register_oauth_callback

_LOGGER = logging.getLogger(__name__)


class AuchanConfigFlow(
    config_entry_oauth2_flow.AbstractOAuth2FlowHandler,
    domain=DOMAIN,
):
    """Handle the Auchan config flow."""

    DOMAIN = DOMAIN
    VERSION = 1

    def __init__(self) -> None:
        """Initialize the config flow."""

        super().__init__()

        self._oauth_data: dict[str, Any] | None = None

        self._display_name = "utilisateur"
        self._email = "Compte Auchan"
        self._rcw_id = "Inconnu"
        self._entry_title = "Compte Auchan"

    @property
    @override
    def logger(self) -> logging.Logger:
        """Return logger."""

        return _LOGGER

    @override
    async def async_step_user(
        self,
        user_input: dict[str, Any] | None = None,
    ) -> ConfigFlowResult:
        """Start the configuration flow."""

        #
        # Only one Auchan account is supported.
        #
        if self.source != SOURCE_REAUTH and self._async_current_entries():
            return self.async_abort(reason="account_already_configured")

        return await self._async_start_oauth()

    async def _async_start_oauth(
        self,
    ) -> ConfigFlowResult:
        """Start Auchan OAuth."""

        #
        # Register our custom OAuth callback.
        #
        async_register_oauth_callback(self.hass)

        #
        # IMPORTANT:
        #
        # Use a dedicated OAuth implementation for
        # this config flow.
        #
        # expected_state and oauth_redirect_uri are
        # specific to this flow.
        #
        self.flow_impl = AuchanOAuth2Implementation(self.hass)

        return await self.async_step_auth()

    @override
    async def async_step_auth(
        self,
        user_input: dict[str, Any] | None = None,
    ) -> ConfigFlowResult:
        """Handle OAuth authorization."""

        if user_input is not None:
            implementation = cast(
                AuchanOAuth2Implementation,
                self.flow_impl,
            )

            expected_state = implementation.expected_state

            received_state = user_input.get("state")

            #
            # OAuth CSRF protection.
            #
            if (
                expected_state is None
                or not isinstance(
                    received_state,
                    str,
                )
                or not secrets.compare_digest(
                    received_state,
                    expected_state,
                )
            ):
                _LOGGER.warning("Auchan OAuth state mismatch")

                return self.async_abort(reason="oauth_failed")

        #
        # Home Assistant handles:
        #
        # user_input is None:
        #   -> external OAuth step
        #
        # user_input contains code/state:
        #   -> external_step_done
        #   -> creation
        #   -> token exchange
        #
        return await super().async_step_auth(user_input)

    @override
    async def async_oauth_create_entry(
        self,
        data: dict[str, Any],
    ) -> ConfigFlowResult:
        """Retrieve Auchan profile after OAuth."""

        #
        # At this point:
        #
        # - authorization code has been exchanged
        # - access_token is available
        # - refresh_token is available
        # - expires_at has been generated by HA
        #
        self._oauth_data = data

        token = data.get("token")

        if not isinstance(token, dict):
            _LOGGER.error("OAuth response did not contain valid token data")

            return self.async_abort(reason="oauth_failed")

        access_token = token.get("access_token")

        if not isinstance(access_token, str) or not access_token:
            _LOGGER.error("OAuth response did not contain an access token")

            return self.async_abort(reason="oauth_failed")

        session = async_get_clientsession(self.hass)

        #
        # Retrieve Auchan profile.
        #
        # This is the only place where the raw
        # access token is used because no ConfigEntry
        # exists yet.
        #
        try:
            profile = await async_get_user_info_for_setup(
                session,
                access_token,
            )

        except ClientError, ValueError:
            _LOGGER.exception("Unable to retrieve Auchan profile")

            return self.async_abort(reason="cannot_connect")

        if not profile.get("authenticated"):
            _LOGGER.error("Auchan user-info returned authenticated=false")

            return self.async_abort(reason="oauth_failed")

        #
        # User information.
        #
        self._display_name = profile.get("given_name") or "utilisateur"

        self._email = profile.get("email") or "Compte Auchan"

        rcw_id = profile.get("rcw_id")

        if rcw_id:
            self._rcw_id = str(rcw_id)

        #
        # Config Entry visible title:
        #
        # <rcw_id> - <email>
        #
        self._entry_title = f"{self._rcw_id} - {self._email}"

        #
        # Technical unique ID.
        #
        account_id = profile.get("rcw_id") or profile.get("email")

        if account_id:
            await self.async_set_unique_id(str(account_id))

            if self.source == SOURCE_REAUTH:
                self._abort_if_unique_id_mismatch(reason="unique_id_mismatch")

            else:
                #
                # Protect against simultaneous
                # setup flows.
                #
                self._abort_if_unique_id_configured()

        #
        # Do NOT create the entry immediately.
        #
        # Show additional successful-login page.
        #
        return await self.async_step_welcome()

    async def async_step_welcome(
        self,
        user_input: dict[str, Any] | None = None,
    ) -> ConfigFlowResult:
        """Show successful authentication."""

        if user_input is None:
            return self.async_show_form(
                step_id="welcome",
                data_schema=probatio.Schema({}),
                description_placeholders={
                    "name": self._display_name,
                    "email": self._email,
                    "rcw_id": self._rcw_id,
                },
                last_step=True,
            )

        if self._oauth_data is None:
            return self.async_abort(reason="oauth_failed")

        #
        # Reauthentication.
        #
        if self.source == SOURCE_REAUTH:
            entry = self._get_reauth_entry()

            self.hass.config_entries.async_update_entry(
                entry,
                title=self._entry_title,
            )

            return self.async_update_reload_and_abort(
                entry,
                data_updates=self._oauth_data,
                reason="reauth_successful",
            )

        #
        # New Config Entry.
        #
        return self.async_create_entry(
            title=self._entry_title,
            data=self._oauth_data,
        )

    @override
    async def async_step_reauth(
        self,
        entry_data: Mapping[str, Any],
    ) -> ConfigFlowResult:
        """Handle reauthentication."""

        return await self._async_start_oauth()
